on:
  push:
    branches: [ "master" ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: grpc-gateway-test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          folder: /tests
          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker-password: ${{ secrets.DOCKERHUB_TOKEN }}
          docker-repository: axel7083/dev
